name: Manual RK322X Kernel Build

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Kernel version to build'
        required: true
        default: '5.10.209'
        type: choice
        options:
          - '5.10.209'
          - '6.1.77'
          - '6.6.30'
      target_branch:
        description: 'Git branch to use'
        required: true
        default: 'main'
        type: string
      clean_build:
        description: 'Perform clean build?'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  manual-build:
    runs-on: ubuntu-22.04
    env:
      KERNEL_VERSION: ${{ inputs.kernel_version }}
      BUILD_BRANCH: ${{ inputs.target_branch }}
      CLEAN_BUILD: ${{ inputs.clean_build }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ env.BUILD_BRANCH }}

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libncurses-dev \
          bison \
          flex \
          libssl-dev \
          libelf-dev \
          gcc-arm-linux-gnueabihf \
          bc \
          git \
          wget \
          kmod \
          cpio \
          python3 \
          rsync \
          xz-utils

    - name: Prepare kernel source
      run: |
        # Extract major.minor version
        KERNEL_MAJOR_MINOR=$(echo ${{ env.KERNEL_VERSION }} | cut -d. -f1-2)
        
        # Download kernel source
        wget https://cdn.kernel.org/pub/linux/kernel/v$KERNEL_MAJOR_MINOR/linux-${{ env.KERNEL_VERSION }}.tar.xz
        
        # Verify download
        if [ ! -f "linux-${{ env.KERNEL_VERSION }}.tar.xz" ]; then
          echo "❌ Kernel source download failed!"
          exit 1
        fi
        
        tar -xf linux-${{ env.KERNEL_VERSION }}.tar.xz
        cd linux-${{ env.KERNEL_VERSION }}
        
        # Clean build if requested
        if [ "${{ env.CLEAN_BUILD }}" = "true" ]; then
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- distclean
          echo "Performed clean build"
        fi

    # ... [langkah-langkah selanjutnya tetap sama] ...
