name: Build RK322X Kernel

on:
  push:
    paths:
      - 'kernel-config/release/rk322x/**'
      - 'kernel-patch/linux-*/**'
  pull_request:
    paths:
      - 'kernel-config/release/rk322x/**'

jobs:
  build-rk322x-kernel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kernel_version: ['5.10', '6.1']  # Versi kernel yang didukung RK322X
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libncurses-dev \
          bison \
          flex \
          libssl-dev \
          libelf-dev \
          gcc-arm-linux-gnueabihf \
          bc

    - name: Prepare kernel source
      run: |
        KERNEL_SERIES=$(echo ${{ matrix.kernel_version }} | cut -d. -f1-2)
        wget https://cdn.kernel.org/pub/linux/kernel/v$KERNEL_SERIES/linux-${{ matrix.kernel_version }}.tar.xz
        tar -xf linux-${{ matrix.kernel_version }}.tar.xz
        cd linux-${{ matrix.kernel_version }}

    - name: Apply RK322X patches
      run: |
        cd linux-${{ matrix.kernel_version }}
        # Apply common patches if any
        for patch in ../kernel-patch/linux-${{ matrix.kernel_version }}.y/*.patch; do
          [ -f "$patch" ] && patch -p1 < "$patch"
        done
        
        # Apply RK322X specific patches
        if [ -d "../kernel-patch/linux-${{ matrix.kernel_version }}.y/rk322x" ]; then
          for patch in ../kernel-patch/linux-${{ matrix.kernel_version }}.y/rk322x/*.patch; do
            [ -f "$patch" ] && patch -p1 < "$patch"
          done
        fi

    - name: Configure kernel for RK322X
      run: |
        cd linux-${{ matrix.kernel_version }}
        cp ../kernel-config/release/rk322x/config-${{ matrix.kernel_version }} .config
        
        # Update configuration for RK322X
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- olddefconfig
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- menuconfig
        
        # Ensure RK322X options are enabled
        ./scripts/config --enable CONFIG_ARCH_ROCKCHIP
        ./scripts/config --enable CONFIG_CPU_RK322X
        ./scripts/config --enable CONFIG_MACH_RK3229
        ./scripts/config --module CONFIG_SND_SOC_RK322X
        
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- olddefconfig

    - name: Build kernel
      run: |
        cd linux-${{ matrix.kernel_version }}
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -j$(nproc) zImage modules dtbs

    - name: Package artifacts
      run: |
        mkdir -p artifacts/rk322x/${{ matrix.kernel_version }}
        cd linux-${{ matrix.kernel_version }}
        cp arch/arm/boot/zImage ../artifacts/rk322x/${{ matrix.kernel_version }}/
        cp arch/arm/boot/dts/rk322x*.dtb ../artifacts/rk322x/${{ matrix.kernel_version }}/
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- modules_install INSTALL_MOD_PATH=../artifacts/rk322x/${{ matrix.kernel_version }}/
        tar -czvf ../artifacts/rk322x-kernel-${{ matrix.kernel_version }}.tar.gz -C ../artifacts/rk322x/${{ matrix.kernel_version }} .

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rk322x-kernel-${{ matrix.kernel_version }}
        path: artifacts/rk322x-kernel-${{ matrix.kernel_version }}.tar.gz
